site_name: TurnBased-poc
theme: 'windmill'
nav:
    # - 'Range intersection': 'range_intersection.md'
    - 'overview': 'overview.md'
extra_javascript:
    - ./js/custom.js
extra_css:
    - ./css/custom.css